# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-javascript/ for more details
#
version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:10.22.0
    steps:
      - checkout
      - run:
          name: npm install
          command: npm i
      - run:
          name: make env
          command: touch .env
      - run:
          name: write api
          command: echo VUE_APP_API_KEY=$FIREBASE_API >> .env
      - run:
          name: write auth domain
          command: echo VUE_APP_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN >> .env
      - run:
          name: write database url
          command: echo VUE_APP_DATABASE_URL=$FIREBASE_DATABASE >> .env
      - run:
          name: write project id
          command: echo VUE_APP_PROJECT_ID=$FIREBASE_PROJECT_ID >> .env
      - run:
          name: write storage
          command: echo VUE_APP_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET >> .env
      - run:
          name: build
          command: npm run build
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
  update-libraries:
    docker:
      - image: circleci/node:10.22.0
    steps:
      - checkout
      - run:
          name: install renovate
          command: sudo npm install renovate -g
      - run:
          name: execute renovate
          command: renovate --platform github --token $GITHUB_API_TOKEN --endpoint https://api.github.com banira0428/TestMaker-Web

workflows:
  version: 2.1
  deploy_master:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
      - update-libraries:
          filters:
            branches:
              only: master




